/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ApplyMethod = IDL.Variant({
  'url' : IDL.Text,
  'email' : IDL.Text,
});
export const JobCategory = IDL.Variant({ 'IT' : IDL.Null, 'NonIT' : IDL.Null });
export const CreateJobRequest = IDL.Record({
  'title' : IDL.Text,
  'salary' : IDL.Opt(IDL.Text),
  'applyMethod' : ApplyMethod,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'category' : JobCategory,
  'requirements' : IDL.Text,
  'location' : IDL.Text,
});
export const JobId = IDL.Nat;
export const Timestamp = IDL.Int;
export const Job = IDL.Record({
  'id' : JobId,
  'title' : IDL.Text,
  'postedAt' : Timestamp,
  'salary' : IDL.Opt(IDL.Text),
  'applyMethod' : ApplyMethod,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'category' : JobCategory,
  'requirements' : IDL.Text,
  'posterPrincipal' : IDL.Principal,
  'location' : IDL.Text,
});
export const CreateProductRequest = IDL.Record({
  'title' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'sellerContact' : IDL.Text,
  'description' : IDL.Text,
  'sellerName' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const ProductId = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'title' : IDL.Text,
  'sellerPrincipal' : IDL.Principal,
  'imageUrls' : IDL.Vec(IDL.Text),
  'listedAt' : Timestamp,
  'sellerContact' : IDL.Text,
  'description' : IDL.Text,
  'sellerName' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'seller' : IDL.Null,
  'employer' : IDL.Null,
  'jobSeeker' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'principal' : IDL.Principal,
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'role' : UserRole,
});
export const JobFilter = IDL.Record({
  'category' : IDL.Opt(JobCategory),
  'keyword' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
});
export const ProductFilter = IDL.Record({
  'category' : IDL.Opt(IDL.Text),
  'keyword' : IDL.Opt(IDL.Text),
});
export const UpdateJobRequest = IDL.Record({
  'id' : JobId,
  'title' : IDL.Text,
  'salary' : IDL.Opt(IDL.Text),
  'applyMethod' : ApplyMethod,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'category' : JobCategory,
  'requirements' : IDL.Text,
  'location' : IDL.Text,
});
export const UpdateProductRequest = IDL.Record({
  'id' : ProductId,
  'title' : IDL.Text,
  'imageUrls' : IDL.Vec(IDL.Text),
  'sellerContact' : IDL.Text,
  'description' : IDL.Text,
  'sellerName' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Float64,
});
export const UpsertProfileRequest = IDL.Record({
  'bio' : IDL.Text,
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'role' : UserRole,
});

export const idlService = IDL.Service({
  'createJob' : IDL.Func([CreateJobRequest], [Job], []),
  'createProduct' : IDL.Func([CreateProductRequest], [Product], []),
  'deleteJob' : IDL.Func([JobId], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'getJob' : IDL.Func([JobId], [IDL.Opt(Job)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
  'initSeed' : IDL.Func([], [], []),
  'listJobs' : IDL.Func([JobFilter], [IDL.Vec(Job)], ['query']),
  'listProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
  'updateJob' : IDL.Func([UpdateJobRequest], [IDL.Bool], []),
  'updateProduct' : IDL.Func([UpdateProductRequest], [IDL.Bool], []),
  'upsertProfile' : IDL.Func([UpsertProfileRequest], [UserProfile], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ApplyMethod = IDL.Variant({ 'url' : IDL.Text, 'email' : IDL.Text });
  const JobCategory = IDL.Variant({ 'IT' : IDL.Null, 'NonIT' : IDL.Null });
  const CreateJobRequest = IDL.Record({
    'title' : IDL.Text,
    'salary' : IDL.Opt(IDL.Text),
    'applyMethod' : ApplyMethod,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'category' : JobCategory,
    'requirements' : IDL.Text,
    'location' : IDL.Text,
  });
  const JobId = IDL.Nat;
  const Timestamp = IDL.Int;
  const Job = IDL.Record({
    'id' : JobId,
    'title' : IDL.Text,
    'postedAt' : Timestamp,
    'salary' : IDL.Opt(IDL.Text),
    'applyMethod' : ApplyMethod,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'category' : JobCategory,
    'requirements' : IDL.Text,
    'posterPrincipal' : IDL.Principal,
    'location' : IDL.Text,
  });
  const CreateProductRequest = IDL.Record({
    'title' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'sellerContact' : IDL.Text,
    'description' : IDL.Text,
    'sellerName' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const ProductId = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'title' : IDL.Text,
    'sellerPrincipal' : IDL.Principal,
    'imageUrls' : IDL.Vec(IDL.Text),
    'listedAt' : Timestamp,
    'sellerContact' : IDL.Text,
    'description' : IDL.Text,
    'sellerName' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'seller' : IDL.Null,
    'employer' : IDL.Null,
    'jobSeeker' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'principal' : IDL.Principal,
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'role' : UserRole,
  });
  const JobFilter = IDL.Record({
    'category' : IDL.Opt(JobCategory),
    'keyword' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
  });
  const ProductFilter = IDL.Record({
    'category' : IDL.Opt(IDL.Text),
    'keyword' : IDL.Opt(IDL.Text),
  });
  const UpdateJobRequest = IDL.Record({
    'id' : JobId,
    'title' : IDL.Text,
    'salary' : IDL.Opt(IDL.Text),
    'applyMethod' : ApplyMethod,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'category' : JobCategory,
    'requirements' : IDL.Text,
    'location' : IDL.Text,
  });
  const UpdateProductRequest = IDL.Record({
    'id' : ProductId,
    'title' : IDL.Text,
    'imageUrls' : IDL.Vec(IDL.Text),
    'sellerContact' : IDL.Text,
    'description' : IDL.Text,
    'sellerName' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Float64,
  });
  const UpsertProfileRequest = IDL.Record({
    'bio' : IDL.Text,
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'role' : UserRole,
  });
  
  return IDL.Service({
    'createJob' : IDL.Func([CreateJobRequest], [Job], []),
    'createProduct' : IDL.Func([CreateProductRequest], [Product], []),
    'deleteJob' : IDL.Func([JobId], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'getJob' : IDL.Func([JobId], [IDL.Opt(Job)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [IDL.Opt(UserProfile)], ['query']),
    'initSeed' : IDL.Func([], [], []),
    'listJobs' : IDL.Func([JobFilter], [IDL.Vec(Job)], ['query']),
    'listProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
    'updateJob' : IDL.Func([UpdateJobRequest], [IDL.Bool], []),
    'updateProduct' : IDL.Func([UpdateProductRequest], [IDL.Bool], []),
    'upsertProfile' : IDL.Func([UpsertProfileRequest], [UserProfile], []),
  });
};

export const init = ({ IDL }) => { return []; };