/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApplyMethod = { 'url' : string } |
  { 'email' : string };
export interface CreateJobRequest {
  'title' : string,
  'salary' : [] | [string],
  'applyMethod' : ApplyMethod,
  'description' : string,
  'company' : string,
  'category' : JobCategory,
  'requirements' : string,
  'location' : string,
}
export interface CreateProductRequest {
  'title' : string,
  'imageUrls' : Array<string>,
  'sellerContact' : string,
  'description' : string,
  'sellerName' : string,
  'category' : string,
  'price' : number,
}
export interface Job {
  'id' : JobId,
  'title' : string,
  'postedAt' : Timestamp,
  'salary' : [] | [string],
  'applyMethod' : ApplyMethod,
  'description' : string,
  'company' : string,
  'category' : JobCategory,
  'requirements' : string,
  'posterPrincipal' : Principal,
  'location' : string,
}
export type JobCategory = { 'IT' : null } |
  { 'NonIT' : null };
export interface JobFilter {
  'category' : [] | [JobCategory],
  'keyword' : [] | [string],
  'location' : [] | [string],
}
export type JobId = bigint;
export interface Product {
  'id' : ProductId,
  'title' : string,
  'sellerPrincipal' : Principal,
  'imageUrls' : Array<string>,
  'listedAt' : Timestamp,
  'sellerContact' : string,
  'description' : string,
  'sellerName' : string,
  'category' : string,
  'price' : number,
}
export interface ProductFilter {
  'category' : [] | [string],
  'keyword' : [] | [string],
}
export type ProductId = bigint;
export type Timestamp = bigint;
export interface UpdateJobRequest {
  'id' : JobId,
  'title' : string,
  'salary' : [] | [string],
  'applyMethod' : ApplyMethod,
  'description' : string,
  'company' : string,
  'category' : JobCategory,
  'requirements' : string,
  'location' : string,
}
export interface UpdateProductRequest {
  'id' : ProductId,
  'title' : string,
  'imageUrls' : Array<string>,
  'sellerContact' : string,
  'description' : string,
  'sellerName' : string,
  'category' : string,
  'price' : number,
}
export interface UpsertProfileRequest {
  'bio' : string,
  'contactInfo' : string,
  'name' : string,
  'role' : UserRole,
}
export interface UserProfile {
  'bio' : string,
  'principal' : Principal,
  'contactInfo' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'role' : UserRole,
}
export type UserRole = { 'seller' : null } |
  { 'employer' : null } |
  { 'jobSeeker' : null };
export interface _SERVICE {
  'createJob' : ActorMethod<[CreateJobRequest], Job>,
  'createProduct' : ActorMethod<[CreateProductRequest], Product>,
  'deleteJob' : ActorMethod<[JobId], boolean>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'getJob' : ActorMethod<[JobId], [] | [Job]>,
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initSeed' : ActorMethod<[], undefined>,
  'listJobs' : ActorMethod<[JobFilter], Array<Job>>,
  'listProducts' : ActorMethod<[ProductFilter], Array<Product>>,
  'updateJob' : ActorMethod<[UpdateJobRequest], boolean>,
  'updateProduct' : ActorMethod<[UpdateProductRequest], boolean>,
  'upsertProfile' : ActorMethod<[UpsertProfileRequest], UserProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];