/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    bio: string;
    principal: Principal;
    contactInfo: string;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
}
export interface UpsertProfileRequest {
    bio: string;
    contactInfo: string;
    name: string;
    role: UserRole;
}
export type Timestamp = bigint;
export type ApplyMethod = {
    __kind__: "url";
    url: string;
} | {
    __kind__: "email";
    email: string;
};
export interface JobFilter {
    category?: JobCategory;
    keyword?: string;
    location?: string;
}
export type JobId = bigint;
export interface CreateJobRequest {
    title: string;
    salary?: string;
    applyMethod: ApplyMethod;
    description: string;
    company: string;
    category: JobCategory;
    requirements: string;
    location: string;
}
export interface ProductFilter {
    category?: string;
    keyword?: string;
}
export interface UpdateJobRequest {
    id: JobId;
    title: string;
    salary?: string;
    applyMethod: ApplyMethod;
    description: string;
    company: string;
    category: JobCategory;
    requirements: string;
    location: string;
}
export interface CreateProductRequest {
    title: string;
    imageUrls: Array<string>;
    sellerContact: string;
    description: string;
    sellerName: string;
    category: string;
    price: number;
}
export interface Job {
    id: JobId;
    title: string;
    postedAt: Timestamp;
    salary?: string;
    applyMethod: ApplyMethod;
    description: string;
    company: string;
    category: JobCategory;
    requirements: string;
    posterPrincipal: Principal;
    location: string;
}
export type ProductId = bigint;
export interface UpdateProductRequest {
    id: ProductId;
    title: string;
    imageUrls: Array<string>;
    sellerContact: string;
    description: string;
    sellerName: string;
    category: string;
    price: number;
}
export interface Product {
    id: ProductId;
    title: string;
    sellerPrincipal: Principal;
    imageUrls: Array<string>;
    listedAt: Timestamp;
    sellerContact: string;
    description: string;
    sellerName: string;
    category: string;
    price: number;
}
export enum JobCategory {
    IT = "IT",
    NonIT = "NonIT"
}
export enum UserRole {
    seller = "seller",
    employer = "employer",
    jobSeeker = "jobSeeker"
}
export interface backendInterface {
    createJob(req: CreateJobRequest): Promise<Job>;
    createProduct(req: CreateProductRequest): Promise<Product>;
    deleteJob(id: JobId): Promise<boolean>;
    deleteProduct(id: ProductId): Promise<boolean>;
    getJob(id: JobId): Promise<Job | null>;
    getMyProfile(): Promise<UserProfile | null>;
    getProduct(id: ProductId): Promise<Product | null>;
    getProfile(principal: Principal): Promise<UserProfile | null>;
    initSeed(): Promise<void>;
    listJobs(filter: JobFilter): Promise<Array<Job>>;
    listProducts(filter: ProductFilter): Promise<Array<Product>>;
    updateJob(req: UpdateJobRequest): Promise<boolean>;
    updateProduct(req: UpdateProductRequest): Promise<boolean>;
    upsertProfile(req: UpsertProfileRequest): Promise<UserProfile>;
}
import type { ApplyMethod as _ApplyMethod, CreateJobRequest as _CreateJobRequest, Job as _Job, JobCategory as _JobCategory, JobFilter as _JobFilter, JobId as _JobId, Product as _Product, ProductFilter as _ProductFilter, Timestamp as _Timestamp, UpdateJobRequest as _UpdateJobRequest, UpsertProfileRequest as _UpsertProfileRequest, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createJob(arg0: CreateJobRequest): Promise<Job> {
        if (this.processError) {
            try {
                const result = await this.actor.createJob(to_candid_CreateJobRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Job_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJob(to_candid_CreateJobRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Job_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProduct(arg0: CreateProductRequest): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0);
            return result;
        }
    }
    async deleteJob(arg0: JobId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJob(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getJob(arg0: JobId): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async initSeed(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initSeed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initSeed();
            return result;
        }
    }
    async listJobs(arg0: JobFilter): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.listJobs(to_candid_JobFilter_n21(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listJobs(to_candid_JobFilter_n21(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProducts(arg0: ProductFilter): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts(to_candid_ProductFilter_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts(to_candid_ProductFilter_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateJob(arg0: UpdateJobRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJob(to_candid_UpdateJobRequest_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJob(to_candid_UpdateJobRequest_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProduct(arg0: UpdateProductRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0);
            return result;
        }
    }
    async upsertProfile(arg0: UpsertProfileRequest): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.upsertProfile(to_candid_UpsertProfileRequest_n28(this._uploadFile, this._downloadFile, arg0));
                return from_candid_UserProfile_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.upsertProfile(to_candid_UpsertProfileRequest_n28(this._uploadFile, this._downloadFile, arg0));
            return from_candid_UserProfile_n16(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ApplyMethod_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplyMethod): ApplyMethod {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_JobCategory_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobCategory): JobCategory {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Job_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Job): Job {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Job]): Job | null {
    return value.length === 0 ? null : from_candid_Job_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    principal: Principal;
    contactInfo: string;
    name: string;
    createdAt: _Timestamp;
    role: _UserRole;
}): {
    bio: string;
    principal: Principal;
    contactInfo: string;
    name: string;
    createdAt: Timestamp;
    role: UserRole;
} {
    return {
        bio: value.bio,
        principal: value.principal,
        contactInfo: value.contactInfo,
        name: value.name,
        createdAt: value.createdAt,
        role: from_candid_UserRole_n18(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _JobId;
    title: string;
    postedAt: _Timestamp;
    salary: [] | [string];
    applyMethod: _ApplyMethod;
    description: string;
    company: string;
    category: _JobCategory;
    requirements: string;
    posterPrincipal: Principal;
    location: string;
}): {
    id: JobId;
    title: string;
    postedAt: Timestamp;
    salary?: string;
    applyMethod: ApplyMethod;
    description: string;
    company: string;
    category: JobCategory;
    requirements: string;
    posterPrincipal: Principal;
    location: string;
} {
    return {
        id: value.id,
        title: value.title,
        postedAt: value.postedAt,
        salary: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.salary)),
        applyMethod: from_candid_ApplyMethod_n10(_uploadFile, _downloadFile, value.applyMethod),
        description: value.description,
        company: value.company,
        category: from_candid_JobCategory_n12(_uploadFile, _downloadFile, value.category),
        requirements: value.requirements,
        posterPrincipal: value.posterPrincipal,
        location: value.location
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    url: string;
} | {
    email: string;
}): {
    __kind__: "url";
    url: string;
} | {
    __kind__: "email";
    email: string;
} {
    return "url" in value ? {
        __kind__: "url",
        url: value.url
    } : "email" in value ? {
        __kind__: "email",
        email: value.email
    } : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    IT: null;
} | {
    NonIT: null;
}): JobCategory {
    return "IT" in value ? JobCategory.IT : "NonIT" in value ? JobCategory.NonIT : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    seller: null;
} | {
    employer: null;
} | {
    jobSeeker: null;
}): UserRole {
    return "seller" in value ? UserRole.seller : "employer" in value ? UserRole.employer : "jobSeeker" in value ? UserRole.jobSeeker : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Job>): Array<Job> {
    return value.map((x)=>from_candid_Job_n7(_uploadFile, _downloadFile, x));
}
function to_candid_ApplyMethod_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApplyMethod): _ApplyMethod {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CreateJobRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateJobRequest): _CreateJobRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_JobCategory_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobCategory): _JobCategory {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_JobFilter_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobFilter): _JobFilter {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_ProductFilter_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductFilter): _ProductFilter {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateJobRequest_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateJobRequest): _UpdateJobRequest {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UpsertProfileRequest_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpsertProfileRequest): _UpsertProfileRequest {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    salary?: string;
    applyMethod: ApplyMethod;
    description: string;
    company: string;
    category: JobCategory;
    requirements: string;
    location: string;
}): {
    title: string;
    salary: [] | [string];
    applyMethod: _ApplyMethod;
    description: string;
    company: string;
    category: _JobCategory;
    requirements: string;
    location: string;
} {
    return {
        title: value.title,
        salary: value.salary ? candid_some(value.salary) : candid_none(),
        applyMethod: to_candid_ApplyMethod_n3(_uploadFile, _downloadFile, value.applyMethod),
        description: value.description,
        company: value.company,
        category: to_candid_JobCategory_n5(_uploadFile, _downloadFile, value.category),
        requirements: value.requirements,
        location: value.location
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    category?: JobCategory;
    keyword?: string;
    location?: string;
}): {
    category: [] | [_JobCategory];
    keyword: [] | [string];
    location: [] | [string];
} {
    return {
        category: value.category ? candid_some(to_candid_JobCategory_n5(_uploadFile, _downloadFile, value.category)) : candid_none(),
        keyword: value.keyword ? candid_some(value.keyword) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none()
    };
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    category?: string;
    keyword?: string;
}): {
    category: [] | [string];
    keyword: [] | [string];
} {
    return {
        category: value.category ? candid_some(value.category) : candid_none(),
        keyword: value.keyword ? candid_some(value.keyword) : candid_none()
    };
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: JobId;
    title: string;
    salary?: string;
    applyMethod: ApplyMethod;
    description: string;
    company: string;
    category: JobCategory;
    requirements: string;
    location: string;
}): {
    id: _JobId;
    title: string;
    salary: [] | [string];
    applyMethod: _ApplyMethod;
    description: string;
    company: string;
    category: _JobCategory;
    requirements: string;
    location: string;
} {
    return {
        id: value.id,
        title: value.title,
        salary: value.salary ? candid_some(value.salary) : candid_none(),
        applyMethod: to_candid_ApplyMethod_n3(_uploadFile, _downloadFile, value.applyMethod),
        description: value.description,
        company: value.company,
        category: to_candid_JobCategory_n5(_uploadFile, _downloadFile, value.category),
        requirements: value.requirements,
        location: value.location
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: string;
    contactInfo: string;
    name: string;
    role: UserRole;
}): {
    bio: string;
    contactInfo: string;
    name: string;
    role: _UserRole;
} {
    return {
        bio: value.bio,
        contactInfo: value.contactInfo,
        name: value.name,
        role: to_candid_UserRole_n30(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    seller: null;
} | {
    employer: null;
} | {
    jobSeeker: null;
} {
    return value == UserRole.seller ? {
        seller: null
    } : value == UserRole.employer ? {
        employer: null
    } : value == UserRole.jobSeeker ? {
        jobSeeker: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "url";
    url: string;
} | {
    __kind__: "email";
    email: string;
}): {
    url: string;
} | {
    email: string;
} {
    return value.__kind__ === "url" ? {
        url: value.url
    } : value.__kind__ === "email" ? {
        email: value.email
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobCategory): {
    IT: null;
} | {
    NonIT: null;
} {
    return value == JobCategory.IT ? {
        IT: null
    } : value == JobCategory.NonIT ? {
        NonIT: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
